version: '3'
services: 
    web:
        stdin_open: true
        build: 
          context: .
          dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - .:/app   
    tests:
        stdin_open: true
        build: 
          context: .
          dockerfile: Dockerfile.dev
        volumes:
            - .:/app
        command: ["npm", "run", "test"]
